[workspace]
resolver = "2"
members = [
    "openlmr-core",
    "version-proxy",
    "git2version",
    "openlmr-voice",
    "openlmr-codeplug",
]

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
