import "./IBMPlexMono-Regular.ttf";
import { Button, VerticalBox, HorizontalBox, StandardListView, TextEdit, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 320px;
    height: 256px;
    in-out property <int> rssi: -999;
    in property <string> zone_channel_description: "Ham/1";
    in property <string> channel_name: "2M Simplex Calling";
    in property <string> freq: "146.52000";
    in property <string> mode: "FM";
    default-font-family: "IBM Plex Mono";
    callback request-increase-value();
    background: #4d004d;
    VerticalBox {
        HorizontalLayout {
            Text {
                text: "OpenLMR";
            }

            Text {
                text: @tr("RSSI: {}db", rssi);
                horizontal-alignment: right;
            }
        }

        Text {
            height: 40px;
            font-size: 24px;
            text: @tr("{}", zone_channel_description);
        }


        Rectangle {
            border-color: white;
            border-width: 2px;
            VerticalBox {
                HorizontalLayout {
                    Text {
                        padding: 8px;
                        font-size: 24px;
                        text: @tr("{} MHz", freq);
                    }

                    Text {
                        horizontal-alignment: right;
                        text: @tr("{}", mode);
                    }
                }

                Text {
                    padding: 8px;
                    font-size: 18px;
                    text: @tr("{}", channel_name);
                }
            }
        }

        HorizontalLayout {
            Rectangle {
                border-color: white;
                border-width: 2px;
                height: 35px;
                width: 100px;
                Text {
                    text: "Menu";
                }
            }

            Rectangle { }

            Rectangle {
                border-color: white;
                border-width: 2px;
                height: 35px;
                width: 100px;
                Text {
                    text: "Channel";
                }
            }
        }
    }
}
