[package]
name = "openlmr-codeplug"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc"] }
postcard = "1.0.0"
embedded-alloc = "0.5.1"
sequential-storage = "1.0.0"
defmt = "0.3.5"
